eureka:
       client:
                 register-with-eureka: false
                 fetch-registry: false
                 serviceUrl:
                           defaultZone: http://localhost:8080/zuul-gateway/eureka
       server:
                 wait-time-in-ms-when-sync-empty: 0
zuul:
      prefix: /api
      routes:
               emp-service:
                       path: /emp-service/**
                       url: http://localhost:8081/emp-service/
               dept-service:
                       path: /dept-service/**
                       url: http://localhost:8082/dept-service/
server:
      servlet:
             context-path: /zuul-gateway
      port: 8080

spring:
      application:
                name: ZUUL-Gateway
      datasource:
                url: jdbc:h2:file:~/deploy-manager/h2db/h2_database
                username: sa
                password: 
                driver-class-name: org.h2.Driver